- name: Create directory and restart Nginx
  hosts: lbservers
  tasks:
    - name: Create directory
      file:
        path: /tmp/logs
        state: directory

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
